[package]
name = "diagrams"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auto_enums = "0.7"
druid = "0.7"
indoc = "1.0"
is_variant = "1.0"
ndarray = "0.15"
nom = "7"
numpy = "0.15"
petgraph = "0.6"
pyo3 = "0.15.1"
sorted-vec = "0.7"
thiserror = "1.0"

[lib]
name = "diagrams"
path = "src/lib.rs"

[[bin]]
name = "parse"
path = "src/parse.rs"

[[bin]]
name = "dot"
path = "src/dot.rs"

[[bin]]
name = "druid"
path = "src/druid.rs"

[[bin]]
name = "tikz"
path = "src/tikz.rs"
