[package]
name = "diagrams"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auto_enums = "0.7"
color-spantrace = "0.2"
dioxus = { path = "../dioxus", features = [ "desktop", "ssr", "web" ] }
futures = "0.3"
indoc = "1.0"
Inflector = "0.11"
is_variant = "1.0"
ndarray = "0.15"
nom = "7"
numpy = "0.15"
petgraph = "0.6"
pyo3 = "0.15.1"
rand = "0.8"
sorted-vec = "0.7"
tao = "0.6"
thiserror = "1.0"
tokio = "1"
tracing = "0.1"
tracing-error = { version = "0.2", features = [ "traced-error" ] }
tracing-subscriber = "0.3"

[dependencies.dioxus-desktop]
git = "https://github.com/dioxuslabs/dioxus"
features = [ "devtool" ]


[target.'cfg(target_os="macos")'.dependencies]
block = "0.1.6"
cocoa = "0.24.0"
objc = "0.2.7"
core-graphics = "0.22.0"
foreign-types = "0.3.2"
bitflags = "1.2.1"

[lib]
name = "diagrams"
path = "src/lib.rs"

[[bin]]
name = "dioxus"
path = "src/dioxus.rs"

[[bin]]
name = "parse"
path = "src/parse.rs"

[[bin]]
name = "objc"
path = "src/objc.rs"

[[bin]]
name = "tikz"
path = "src/tikz.rs"
