[package]
name = "dioxus"
version = "0.1.0"
edition = "2021"

[dependencies]
color-spantrace = "0.2"
diagrams = { path = "..", default-features = false, features = [ "cvxpy", "gui", "minion" ] }
dioxus = { version = "0.2", features = ["desktop"] }
dioxus-desktop = { version = "0.2" }
futures = "0.3"
indoc = "1.0"
Inflector = "0.11"
nom = "7"
petgraph = { version = "0.6", features = ["serde-1"] }
serde = "1"
serde_json = "1"
tao = "0.6"
tokio = { version = "1", features = [ "rt-multi-thread" ] }
tracing = "0.1"
tracing-error = { version = "0.2", features = [ "traced-error" ] }
tracing-subscriber = "0.3"